spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c72auqk86wix.ap-northeast-2.rds.amazonaws.com:3306/todoProject?serverTimezone=Asia/Seoul
    username: admin
    password: ckawhgdmsryghl1!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        format_sql: true